echo ""
echo "Notes: "
echo "  The first thing to do: see if you need to install stuff"
echo "    #sudo apt-get install tasksel"
echo "    #sudo tasksel install lamp-server"
echo "    sudo apt-get install apache2"
echo "    sudo apt-get install php5 libapache2-mod-php5"
echo "    http://www.howtoforge.com/installing-apache2-with-php5-and-mysql-support-on-ubuntu-12.04-lts-lamp"
echo "    sudo apt-get install php5-mysql"
echo "  The second thing to do: alter jon.properties"
echo "  The third thing to do: sudo ant deploy -> creates deployment dirs in apache dir"
echo "  The fourth thing to do: run ddl.sql"
echo ""
echo ""

echo "To restart apache: /etc/init.d/apache2 restart"
